# These are supported funding model platforms

# github: [hedzr]
open_collective: android-file-chooser
# custom: https://paypal.me/hezr/5
custom: https://paypal.me/hezr/3
# custom: https://paypal.me/hezr/20
